source 'https://rubygems.org/'

gem 'tumblr_client'
gem 'sanitize'
gem 'marky_markov'
gem 'activerecord'
gem 'logger'
gem 'sentimental'
gem 'sqlite3'
gem 'colorize'
gem 'pxlsrt'
gem 'mini_magick'
gem 'midilib'
gem 'rest_client'
